# sudo: false

language: node_js

os: windows

node_js:
 - node

# install:
# - npm ci

script:
- npm run test:coveralls

addons:
  sonarcloud:
    organisation: "antidern"
script:
 - sonar-scanner


