language: node_js

sudo: false

node_js:
- node

# mono: none

# dotnet: 2.0.3
install:
- npm ci

script:
- npm test

notifications:
  email:
    recipients:
      - dmitidern@mail.ru
    on_success: never 
    on_failure: always 