language: js

mono: none

dotnet: 2.0.3

# script:

# - dotnet restore TextCensoring.csproj

notifications:
  email:
    recipients:
      - dmitidern@mail.ru
    on_success: never # default: change
    on_failure: always # default: always